### ISSUE TITLE
User profile avatar should be seen in notifications

### ISSUE THREAD

**Issue by Israellund** [hicommonwealth/commonwealth#10264]
## Describe the bug

Community profile avatar should be seen in notifications to look similar to when a user comments or replies to you. 

![395262753-973f12b2-a802-4bb5-82b0-cb30f8ecb72a](https://github.com/user-attachments/assets/9fe675d4-c53d-48cd-b73b-3b7da96e0956)

**Comment by sachben91** [comment]
@Israellund @KaleemNeslit I see there is a PR up for this, want to know if we can close this or not

**Comment by KaleemNeslit** [comment]
> @Israellund @KaleemNeslit I see there is a PR up for this, want to know if we can close this or not

@sachben91  here we are blocked as we  need to sent user avatar from the backend here is the open ticket for this [task](https://github.com/hicommonwealth/commonwealth/issues/10279)

**Comment by KaleemNeslit** [comment]
here  i am blocked not able to receive userAvatar in actor or data  
@dillchen

**Comment by Rotorsoft** [comment]
I added actor profile details to the requested notification handlers in this PR: https://github.com/hicommonwealth/commonwealth/pull/10637  (merged on Jan 27)

Are we discussing new notifications here?

**Comment by dillchen** [comment]
Nope looks like that resolves, now just need to test and ensure it's working in Knock

**Comment by KaleemNeslit** [comment]
> Nope looks like that resolves, now just need to test and ensure it's working in Knock

i am on it @dillchen

**Comment by KaleemNeslit** [comment]
@dillchen @Rotorsoft i tested the notification locally i am still not able to received actor data .

![Image](https://github.com/user-attachments/assets/8f7d043d-23fd-4ec2-83d3-6594dd2dea38)

**Comment by Rotorsoft** [comment]
@KaleemNeslit can you provide more details about how you arrived to this notification? I need to be able to reproduce it on my local.

**Comment by KaleemNeslit** [comment]
> [@KaleemNeslit](https://github.com/KaleemNeslit) can you provide more details about how you arrived to this notification? I need to be able to reproduce it on my local.
run the following locally  @Rotorsoft 
pnpm -F commonwealth start
Run RabbitMQ in Docker
pnpm -F commonwealth  start-message-relayer
pnpm -F commonwealth start-knock
Use 2 accounts to trigger thread/comment notifications on 1st account .
i.e create thread from account 1 and added comment from 2nd account . 
make sure you are able to see notification bell icon on frontend . if not maybe need to update knock env 

![Image](https://github.com/user-attachments/assets/b495015c-ca81-4798-9a77-cc90e2d2c07e)

**Comment by Rotorsoft** [comment]
yeah, that's what I'm doing, and this is the logged payload before sending it to knock:

```
################## {
  key: 'comment-creation',
  users: [ { id: '128620' } ],
  data: {
    author: 'importanttransmitter48',
    comment_parent_name: 'thread',
    community_name: 'Meat',
    comment_body: 'third comment',
    comment_url: 'http://localhost:8080/meat/discussion/26592?comment=90630',
    comment_created_event: {
      id: 90630,
      thread_id: 26592,
      address_id: 208271,
      body: 'third comment',
      parent_id: null,
      content_url: null,
      comment_level: 0,
      canvas_signed_data: '{"actionMessage":{"clock":4,"parents":["0e0jaeq97lpbuk7v4n639m8cj9009cg0"],"payload":{"args":{"body":"third comment\\n","parent_comment_id":null,"thread_id":"0b5sdhs9tjittj6onj8n6uq2ao1ttn21"},"context":{"timestamp":1741370210181},"did":"did:pkh:eip155:1:0x83ef500a9CB761baE639b09Ff989686558e86B00","name":"comment","type":"action"},"topic":"common.xyz"},"actionMessageSignature":{"codec":"dag-cbor","publicKey":"did:key:z6MknwdiPw3n2T7dGcMjWkGM1R39hcvXzyrCDxLehiVSnJZa","signature":{"/":{"bytes":"lZRnE1yggKDDDr9xlo1BoVahVhDf+KivSsdMpkumkRxK3tkIov6oPs/1Pdu+zljDtb1YisHpk0h9RWH48tinCQ"}}},"sessionMessage":{"clock":3,"parents":["09pjc6dlj0nrerj6ib7vicgs81bgmgtg"],"payload":{"authorizationData":{"domain":"localhost:8080","nonce":"7lVZB9QFB9YEBMpOY","signature":{"/":{"bytes":"FnWIusDm5Q2obbXIHSLFPqePko5bx0TUHP1Tn4kBBYNEsotObpvbUZXYgyc0CtBitikI3eDmibRdSUlRcOOcWhs"}}},"context":{"timestamp":1741370005607},"did":"did:pkh:eip155:1:0x83ef500a9CB761baE639b09Ff989686558e86B00","publicKey":"did:key:z6MknwdiPw3n2T7dGcMjWkGM1R39hcvXzyrCDxLehiVSnJZa","type":"session"},"topic":"common.xyz"},"sessionMessageSignature":{"codec":"dag-cbor","publicKey":"did:key:z6MknwdiPw3n2T7dGcMjWkGM1R39hcvXzyrCDxLehiVSnJZa","signature":{"/":{"bytes":"qcB1Z/1KHcb7sFW2UmQ2IRnAzINHjJ34Ti41r9YvQyB76k0pXg4Pjr1aBkyg2hNiZq2l952UJ314QUgJYN7QAQ"}}}}',
      canvas_msg_id: '0g2ajf6sj6iu8k6u56tqr2r2ko9um3qb',
      created_by: '',
      created_at: 2025-03-07T17:56:50.228Z,
      updated_at: 2025-03-07T17:56:50.228Z,
      deleted_at: null,
      marked_as_spam_at: null,
      discord_meta: null,
      reply_count: 0,
      reaction_count: 0,
      reaction_weights_sum: '0',
      community_id: 'meat',
      users_mentioned: []
    }
  },
  actor: {
    id: '162737',
    profile_name: 'importanttransmitter48',
    profile_url: 'http://localhost:8080/profile/id/162737',
    email: undefined,
    profile_avatar_url: 'https://assets.commonwealth.im/0847e7f5-4d96-4406-8f30-c3082fa2f27c.png'
  }
}
```

**Comment by dillchen** [comment]
@Rotorsoft for clarity I think it's just the upvote notification

**Comment by KaleemNeslit** [comment]
> yeah, that's what I'm doing, and this is the logged payload before sending it to knock:
> 
> ```
> ################## {
>   key: 'comment-creation',
>   users: [ { id: '128620' } ],
>   data: {
>     author: 'importanttransmitter48',
>     comment_parent_name: 'thread',
>     community_name: 'Meat',
>     comment_body: 'third comment',
>     comment_url: 'http://localhost:8080/meat/discussion/26592?comment=90630',
>     comment_created_event: {
>       id: 90630,
>       thread_id: 26592,
>       address_id: 208271,
>       body: 'third comment',
>       parent_id: null,
>       content_url: null,
>       comment_level: 0,
>       canvas_signed_data: '{"actionMessage":{"clock":4,"parents":["0e0jaeq97lpbuk7v4n639m8cj9009cg0"],"payload":{"args":{"body":"third comment\\n","parent_comment_id":null,"thread_id":"0b5sdhs9tjittj6onj8n6uq2ao1ttn21"},"context":{"timestamp":1741370210181},"did":"did:pkh:eip155:1:0x83ef500a9CB761baE639b09Ff989686558e86B00","name":"comment","type":"action"},"topic":"common.xyz"},"actionMessageSignature":{"codec":"dag-cbor","publicKey":"did:key:z6MknwdiPw3n2T7dGcMjWkGM1R39hcvXzyrCDxLehiVSnJZa","signature":{"/":{"bytes":"lZRnE1yggKDDDr9xlo1BoVahVhDf+KivSsdMpkumkRxK3tkIov6oPs/1Pdu+zljDtb1YisHpk0h9RWH48tinCQ"}}},"sessionMessage":{"clock":3,"parents":["09pjc6dlj0nrerj6ib7vicgs81bgmgtg"],"payload":{"authorizationData":{"domain":"localhost:8080","nonce":"7lVZB9QFB9YEBMpOY","signature":{"/":{"bytes":"FnWIusDm5Q2obbXIHSLFPqePko5bx0TUHP1Tn4kBBYNEsotObpvbUZXYgyc0CtBitikI3eDmibRdSUlRcOOcWhs"}}},"context":{"timestamp":1741370005607},"did":"did:pkh:eip155:1:0x83ef500a9CB761baE639b09Ff989686558e86B00","publicKey":"did:key:z6MknwdiPw3n2T7dGcMjWkGM1R39hcvXzyrCDxLehiVSnJZa","type":"session"},"topic":"common.xyz"},"sessionMessageSignature":{"codec":"dag-cbor","publicKey":"did:key:z6MknwdiPw3n2T7dGcMjWkGM1R39hcvXzyrCDxLehiVSnJZa","signature":{"/":{"bytes":"qcB1Z/1KHcb7sFW2UmQ2IRnAzINHjJ34Ti41r9YvQyB76k0pXg4Pjr1aBkyg2hNiZq2l952UJ314QUgJYN7QAQ"}}}}',
>       canvas_msg_id: '0g2ajf6sj6iu8k6u56tqr2r2ko9um3qb',
>       created_by: '',
>       created_at: 2025-03-07T17:56:50.228Z,
>       updated_at: 2025-03-07T17:56:50.228Z,
>       deleted_at: null,
>       marked_as_spam_at: null,
>       discord_meta: null,
>       reply_count: 0,
>       reaction_count: 0,
>       reaction_weights_sum: '0',
>       community_id: 'meat',
>       users_mentioned: []
>     }
>   },
>   actor: {
>     id: '162737',
>     profile_name: 'importanttransmitter48',
>     profile_url: 'http://localhost:8080/profile/id/162737',
>     email: undefined,
>     profile_avatar_url: 'https://assets.commonwealth.im/0847e7f5-4d96-4406-8f30-c3082fa2f27c.png'
>   }
> }
> ```

yes i also saw that payload is correct maybe there is something with the knock not correctly mapping it .
you can also send profile_avatar_url in data i will extract from there . just made is mandatory for every notification to have it. if it can help to resolve issue   @Rotorsoft

**Comment by Rotorsoft** [comment]
seems like the issue is having the actor schema outside the data schema... this PR should fix it:

https://github.com/hicommonwealth/commonwealth/pull/11337

**Comment by KaleemNeslit** [comment]
> seems like the issue is having the actor schema outside the data schema... this PR should fix it:
> 
> [#11337](https://github.com/hicommonwealth/commonwealth/pull/11337)

@Rotorsoft  i checked out into your branch `rotorsoft/10264-use-author-schema
` still not able to received actor value or avatar_url
<img width="560" alt="Image" src="https://github.com/user-attachments/assets/39297b20-51d1-474c-9526-a32a8bff29c4" />

**Comment by Rotorsoft** [comment]
Make sure the new knock messages looks like this:

```
{
  "author": "upcomingpreservative21",
  "author_address": "0x83ef500a9CB761baE639b09Ff989686558e86B00",
  "author_address_id": 208271,
  "author_avatar_url": "https://assets.commonwealth.im/0847e7f5-4d96-4406-8f30-c3082fa2f27c.png",
  "author_profile_url": "http://localhost:8080/profile/id/162737",
  "author_user_id": "162737",
  "comment_body": "abc",
  "comment_created_event": {
    "address_id": 208271,
    "body": "abc",
    "canvas_msg_id": "08oans9ml2dk78m59m7smje7j9o43ua9",
    "canvas_signed_data": "{\"actionMessage\":{\"clock\":2,\"parents\":[\"04bm8r6pp6dbpr36kt3c4vn0pokr2r51\"],\"payload\":{\"args\":{\"body\":\"abc\\n\",\"parent_comment_id\":null,\"thread_id\":\"0b5sdhs9tjittj6onj8n6uq2ao1ttn21\"},\"context\":{\"timestamp\":1741380816463},\"did\":\"did:pkh:eip155:1:0x83ef500a9CB761baE639b09Ff989686558e86B00\",\"name\":\"comment\",\"type\":\"action\"},\"topic\":\"common.xyz\"},\"actionMessageSignature\":{\"codec\":\"dag-cbor\",\"publicKey\":\"did:key:z6Mkq6xvYtEoSuhey6db8GVbGVg2zywUDbYpxP9XaaWjkcoz\",\"signature\":{\"/\":{\"bytes\":\"L9aTCSGE8MOc812PRKFCKR3TwwIp9TjHPXy9WPs4r1PI9oYYLb+k7rGnhXPBtHiNJAsGpL/Zw23/jz5pjBZFCw\"}}},\"sessionMessage\":{\"clock\":1,\"parents\":[],\"payload\":{\"authorizationData\":{\"domain\":\"localhost:8080\",\"nonce\":\"sVbc0U3UIwDXpLqf3\",\"signature\":{\"/\":{\"bytes\":\"CHEz+fD9S6h4AYfepsWOlrhmZmUHTByegDxhkRCFWAsfaH25A4loIaxUN3xGkvEW8lRXLvQ10LwW7z/RuYlo5Rs\"}}},\"context\":{\"timestamp\":1741378213774},\"did\":\"did:pkh:eip155:1:0x83ef500a9CB761baE639b09Ff989686558e86B00\",\"publicKey\":\"did:key:z6Mkq6xvYtEoSuhey6db8GVbGVg2zywUDbYpxP9XaaWjkcoz\",\"type\":\"session\"},\"topic\":\"common.xyz\"},\"sessionMessageSignature\":{\"codec\":\"dag-cbor\",\"publicKey\":\"did:key:z6Mkq6xvYtEoSuhey6db8GVbGVg2zywUDbYpxP9XaaWjkcoz\",\"signature\":{\"/\":{\"bytes\":\"mevTLOVattQ/IUxcoFJXGRvfi5LlEzvd2aWjaLRr+r5HnWyrUP1+PwXsqe54TcAOvTbxDGEIwwztIFb8PpgzCQ\"}}}}",
    "comment_level": 0,
    "community_id": "meat",
    "content_url": null,
    "created_at": "2025-03-07T20:53:36.506Z",
    "created_by": "",
    "deleted_at": null,
    "discord_meta": null,
    "id": 90633,
    "marked_as_spam_at": null,
    "parent_id": null,
    "reaction_count": 0,
    "reaction_weights_sum": "0",
    "reply_count": 0,
    "thread_id": 26592,
    "updated_at": "2025-03-07T20:53:36.506Z",
    "users_mentioned": []
  },
  "comment_parent_name": "thread",
  "comment_url": "http://localhost:8080/meat/discussion/26592?comment=90633",
  "community_name": "Meat"
}
```
